### ISSUE TITLE
XLRDError at /import/import_options/

### ISSUE THREAD

**Issue by glynjackson** [pstch/django-batchimport#1]
XLRDError at /import/import_options/

Unsupported format, or corrupt file: Expected BOF record; found 'glyn,082'

Request Method:     GET
Request URL:    http://127.0.0.1:8001/import/import_options/
Django Version:     1.5.1
Exception Type:     XLRDError
Exception Value:    

Unsupported format, or corrupt file: Expected BOF record; found 'glyn,082'

Exception Location:     /Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/xlrd/book.py in bof_error, line 1252
Python Executable:  /Users/user/Documents/workspace/livewireSMS/django-env/bin/python
Python Version:     2.7.2
Python Path:    

['/Users/user/Documents/workspace/LiveWireSMS',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/gunicorn-0.17.2-py2.7.egg',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python27.zip',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/plat-darwin',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/plat-mac',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/user/Documents/workspace/livewireSMS/django-env/Extras/lib/python',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/lib-tk',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/lib-old',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/PIL',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/newrelic-1.11.0.55']

**Comment by pstch** [comment]
What kind of file did you send to django-batchimport ? It only reads XLS files, not XLSX or CSV.

**Comment by glynjackson** [comment]
Sorry yes, you did state 'CSV files _saved_ as Excel' and not CSV files themselves, my bad.

**Comment by pstch** [comment]
You were right this was not clear. I updated the description.
