### ISSUE TITLE
Numbers in xls won't import

### ISSUE THREAD

**Issue by glynjackson** [pstch/django-batchimport#2]
AttributeError at /import/import_options/

'float' object has no attribute 'lower'

Request Method:     GET
Request URL:    http://127.0.0.1:8001/import/import_options/
Django Version:     1.5.1
Exception Type:     AttributeError
Exception Value:    

'float' object has no attribute 'lower'

Exception Location:     /Users/user/Documents/workspace/LiveWireSMS/batchimport/forms.py in _get_initial_value, line 145
Python Executable:  /Users/user/Documents/workspace/livewireSMS/django-env/bin/python
Python Version:     2.7.2
Python Path:    

['/Users/user/Documents/workspace/LiveWireSMS',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/gunicorn-0.17.2-py2.7.egg',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python27.zip',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/plat-darwin',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/plat-mac',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/user/Documents/workspace/livewireSMS/django-env/Extras/lib/python',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/lib-tk',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/lib-old',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/PIL',
 '/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/newrelic-1.11.0.55']

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8001/import/import_options/

Django Version: 1.5.1
Python Version: 2.7.2
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.humanize',
 'south',
 'userena',
 'social_auth',
 'djcelery',
 'storages',
 'endless_pagination',
 'django.contrib.flatpages',
 'django_sagepay',
 'guardian',
 'accounts',
 'contacts',
 'sms',
 'smartpages',
 'shorturl',
 'django_sagepay',
 'batchimport',
 'debug_toolbar')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'async_messages.middleware.AsyncMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:
File "/Users/user/Documents/workspace/livewireSMS/django-env/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/Users/user/Documents/workspace/LiveWireSMS/batchimport/views.py" in import_options
2.      form = ImportOptionsForm(model_for_import, save_file_name)
   File "/Users/user/Documents/workspace/LiveWireSMS/batchimport/forms.py" in **init**
3.               initial_value = self._get_initial_value(xls_column_option_list, base_field_name)
   File "/Users/user/Documents/workspace/LiveWireSMS/batchimport/forms.py" in _get_initial_value
4.          if field_name.lower() == choice.lower():

Exception Type: AttributeError at /import/import_options/
Exception Value: 'float' object has no attribute 'lower'

**Comment by pstch** [comment]
I'll look in this one.

**Comment by bolshoibooze** [comment]
Just make sure all your excel column names are strings/chars and not numbers
