### ISSUE TITLE
How do you add foreign keys?

### ISSUE THREAD

**Issue by glynjackson** [pstch/django-batchimport#3]

**Comment by glynjackson** [comment]
It would be good if you could add FK dynamically

**Comment by pstch** [comment]
What do you mean ? django-batchimport can understand mappings, and allows you to fill FK fields from the spreadsheet using the mapping field you define in the import options.

**Comment by glynjackson** [comment]
This would be more of a feature request / question than a bug sorry. I was wondering if it was possible assign a FK relationship so the user does not have to pick add the ID's in their spreadsheet.

**Comment by pstch** [comment]
I'm sorry I'm failing to understand what you mean. If could try expanding a bit, or giving me an example of this, this would be great.

Also, don't really have the time today to look deeper into that matter, I'll give it a look tomorrow.
